language: java
jdk: openjdk7
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "
if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then
    mvn clean deploy --settings target/travis/settings.xml;
else
    mvn clean verify --settings target/travis/settings.xml;
fi"

# whitelist
branches:
  only:
    - develop

env:
  global:
  - secure: XbsunKkhAqV2Jag7Maj+SGJ2JsdIzr9E9h1jU+mhTWqmEBYbHTOQXlPjcterzO7bq+kLZgFGJlpa+uQbt/D1e767k9LqoG6HGxijDTnFZRaZQhjWITr13SIatRtuntQWgOwIuzpy92nRElFh6XzN56Jhv93fQ0ZO0KrD6tqMDmc=
  - secure: IuNv2W2OrQy1rX4Bqy566peRw1o8imPow4niDQ1soB+yjNd2Hk8RAWRhMPuQ8WLvxRKmDyfPC1WMs5kxKYp4zydfZwZ5JHFRWtMAbuLI74vXVqv+EhQC5snCvWRIHxGUT28tnrpnAhRFvXXLFdJJ6YbIRvSj4Ptrb87uupMSg1s=
